task_name: afrixnli_direct
task_template: afrixnli_{{language}}_prompt_1,afrixnli_{{language}}_prompt_2,afrixnli_{{language}}_prompt_3,afrixnli_{{language}}_prompt_4,afrixnli_{{language}}_prompt_5
wandb_project: afribench-afrixnli-direct
wandb_job_type: eval
languages:
  - amh
  - eng
  - ewe
  - fra
  - hau
  - ibo
  - kin
  - lin
  - lug
  - orm
  - sna
  - sot
  - swa
  - twi
  - wol
  - xho
  - yor
  - zul
