model_name: /home/oogundep/runs/grade_school_math_llama_3_8b_base_no_instruction_mask
revision: main
trust_remote_code: true
parallelize: false
add_bos_token: false
model_type: hf
languages_supported:
  - eng