task_name: xl_sum
task_template: xl_sum_{{language}}_prompt_1,xl_sum_{{language}}_prompt_2,xl_sum_{{language}}_prompt_3
wandb_project: afribench-xl-sum
wandb_job_type: eval
prompt_directory: runs/xl_sum/prompts
hub_dataset: csebuetnlp/xlsum
evaluation_split: test
languages:
  - amharic
  - arabic
  - hausa
  - igbo
  - kirundi
  - oromo
  - pidgin
  - somali
  - swahili
  - tigrinya
  - yoruba
  - english
  - french

